### ISSUE TITLE
error:local variable 'X_train' referenced before assignment

### ISSUE THREAD

**Issue by 008karan** [jindongwang/Deep-learning-activity-recognition#1]
whenever run the script gives "local variable 'X_train' referenced before assignment".

**Comment by jindongwang** [comment]
Did you download the dataset well?

**Comment by 008karan** [comment]
It's working now!
I am not getting how you preprocessed the data? As original dataset has **19 actions done by 8 people and each signal is divided into 60 segments.** How you converted this whole data to **X_train, Y_train.**
I am going to apply different algorithms to this so need clarification in preprocessing step. Thanks!

**Comment by jindongwang** [comment]
@008karan  It is basic sliding-window technique. And then we can extract features.
