### ISSUE TITLE
输入channel为何是9？

### ISSUE THREAD

**Issue by henbucuoshanghai** [jindongwang/Deep-learning-activity-recognition#9]
# X, Y and keep_prob are three feeds to the network
    X = tf.placeholder(tf.float32, shape=[None, config.input_height, config.input_width, config.n_channel])

你好：为何是9呢？视频 切成一帧zhen?

**Comment by jindongwang** [comment]
这不是视频，这是时间序列。请仔细阅读数据集介绍。
